project_id = "snawpxrejmcxfbiiowxr"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.notify-session]
    verify_jwt = false
  [functions.session-reminders]
    verify_jwt = true
  [functions.report-bug]
    verify_jwt = false
  [functions.send-campaign-invitation]
    verify_jwt = true

  [functions.payments-webhook]
    verify_jwt = false
  [functions.paddle-portal]
    verify_jwt = true
