import { Link } from "react-router-dom";
import type { ReactNode } from "react";
import LegalLayout, { LegalList, LegalSection } from "@/components/legal/LegalLayout";
import LegalRequestForm from "@/components/legal/LegalRequestForm";

const identity = <address className="not-italic">Erwan Didier Valery Lesage<br />Entrepreneur individuel — Micro-entreprise<br />Nom commercial : Aétheria VTT<br />SIREN : 109 326 066<br />41 La Codelais, 22630 Saint-Judoce, France<br /><a className="text-primary underline" href="mailto:erwanlesagepro@gmail.com">erwanlesagepro@gmail.com</a><br /><a className="text-primary underline" href="tel:+33661549615">06 61 54 96 15</a></address>;
const contact = <a className="text-primary underline" href="mailto:erwanlesagepro@gmail.com">erwanlesagepro@gmail.com</a>;

export function LegalNotices() {
  return <LegalLayout title="Mentions légales" description="Informations légales relatives à l’édition et à l’exploitation d’Aétheria VTT." path="/mentions-legales">
    <LegalSection title="1 à 7. Éditeur, identité et activité">{identity}<p>Site : <a className="text-primary underline" href="https://aetheriavtt.com">https://aetheriavtt.com</a></p><p>Responsable de publication : Erwan Didier Valery Lesage.</p><p>Activité : exploitation et commercialisation d’une plateforme numérique en ligne de table virtuelle destinée aux jeux de rôle, proposant des services numériques, des fonctionnalités de jeu, des contenus numériques et des abonnements payants.</p></LegalSection>
    <LegalSection title="8. Hébergeur"><address className="not-italic">Lovable Labs AB<br />Regeringsgatan 25<br />111 53 Stockholm<br />Suède</address><a className="text-primary underline" href="https://lovable.dev" target="_blank" rel="noreferrer">https://lovable.dev</a></LegalSection>
    <LegalSection title="9. Contact"><p>Pour toute question concernant le site : {contact} ou 06 61 54 96 15.</p></LegalSection>
    <LegalSection title="10. Propriété intellectuelle"><p>La structure, l’identité visuelle, le logiciel et les contenus originaux Aétheria sont protégés. Toute reproduction non autorisée peut constituer une contrefaçon. Les contenus importés restent la propriété de leurs titulaires.</p></LegalSection>
    <LegalSection title="11. Marques et systèmes tiers"><p>Les noms, marques, logos, univers et contenus tiers restent la propriété de leurs détenteurs. Aétheria VTT ne revendique aucun droit sur ces éléments. Les autorisations Worlds Awakening et Glyphes sont décrites dans les <Link className="text-primary underline" to="/credits-licences">Crédits & licences</Link>.</p></LegalSection>
    <LegalSection title="12. Responsabilité"><p>Aétheria VTT met en œuvre des moyens raisonnables pour fournir le service, sans garantir une disponibilité ininterrompue. L’utilisateur demeure responsable de son usage du service, de ses sauvegardes et des contenus qu’il publie ou importe.</p></LegalSection>
    <LegalSection title="13. Liens externes"><p>Les liens vers des services tiers sont fournis pour leur utilité. Aétheria VTT ne contrôle pas leur contenu, leurs conditions ou leur disponibilité.</p></LegalSection>
    <LegalSection title="14. Données personnelles"><p>Les traitements réellement identifiés et les droits des personnes sont détaillés dans la <Link className="text-primary underline" to="/confidentialite">Politique de confidentialité</Link>.</p></LegalSection>
    <LegalSection title="15. Cookies"><p>Les stockages techniques et de préférences utilisés sont décrits dans la <Link className="text-primary underline" to="/cookies">Politique cookies</Link>. Aucun traceur statistique ou publicitaire n’a été identifié dans la version auditée.</p></LegalSection>
    <LegalSection title="16. Mise à jour"><p>La présente version entre en vigueur en septembre 2026. Toute modification substantielle sera datée et portée à la connaissance des utilisateurs par un moyen approprié.</p></LegalSection>
  </LegalLayout>;
}

const cguArticles: Array<[string, ReactNode]> = [
  ["Article 1 — Objet", <p>Les présentes CGU encadrent l’accès et l’utilisation de la plateforme Aétheria VTT.</p>],
  ["Article 2 — Définitions", <p>« Service » désigne Aétheria VTT ; « utilisateur » toute personne accédant au Service ; « MJ » le gestionnaire d’une campagne ; « contenu utilisateur » tout élément créé, importé, stocké ou partagé.</p>],
  ["Article 3 — Accès au service", <p>Les pages publiques sont librement accessibles. Les campagnes, personnages, fichiers et fonctions personnelles nécessitent un compte. L’utilisateur doit disposer d’un équipement et d’une connexion compatibles.</p>],
  ["Article 4 — Création d’un compte", <p>L’utilisateur fournit une adresse e-mail valide, un mot de passe et, s’il le souhaite, un nom d’aventurier. La connexion Google est également proposée. Les informations doivent être exactes et tenues à jour.</p>],
  ["Article 5 — Sécurité du compte", <p>L’utilisateur protège ses identifiants, ne les partage pas et signale rapidement tout accès suspect. Il est responsable des actions effectuées depuis son compte sauf preuve d’un usage frauduleux.</p>],
  ["Article 6 — Utilisation du VTT", <p>Le Service permet notamment l’usage d’une table virtuelle, de cartes, tokens, dés, chat, scènes, murs, lumières, audio et outils de partie, selon les fonctions disponibles et le rôle accordé.</p>],
  ["Article 7 — Campagnes", <p>Le MJ organise ses campagnes, invite les participants et attribue leurs droits. Les participants respectent les règles de la campagne et les décisions de modération légitimes du MJ.</p>],
  ["Article 8 — Personnages", <p>Chaque système conserve ses propres règles et fiches. L’utilisateur est responsable des informations saisies. Les droits de consultation et de modification dépendent du rôle et de la propriété du personnage.</p>],
  ["Article 9 — Codex", <p>Le Codex réunit des contenus Aétheria, autorisés, sous licence ou créés par les utilisateurs. La disponibilité d’une entrée ne transfère aucun droit de propriété intellectuelle.</p>],
  ["Article 10 — Contenus utilisateurs", <><p>L’utilisateur reste titulaire des droits qu’il possède sur ses contenus. Il garantit disposer des droits nécessaires pour les importer, stocker ou partager.</p><p>Il accorde uniquement les droits techniques nécessaires à l’hébergement, au stockage, à la sauvegarde, à l’affichage, à la transmission et au traitement technique du contenu pour fournir le Service. Aétheria VTT n’en devient pas propriétaire.</p></>],
  ["Article 11 — Fichiers importés", <p>Images, cartes, tokens, PDF, documents et fichiers audio doivent respecter les formats, tailles, quotas et droits applicables. L’utilisateur conserve une copie des fichiers importants.</p>],
  ["Article 12 — Contenus publics", <p>L’utilisateur qui rend un contenu public en assume la responsabilité et respecte les droits d’auteur, la vie privée et la loi. Un contenu manifestement illicite ou contrefaisant peut être masqué ou retiré après examen.</p>],
  ["Article 13 — Homebrew", <p>Le Homebrew permet des créations personnalisées. Leur auteur reste responsable de leur originalité, de leur exactitude, de leur partage et de leur compatibilité avec les droits de tiers.</p>],
  ["Article 14 — Comportements interdits", <LegalList items={["porter atteinte à un tiers, harceler, frauder ou usurper une identité", "importer un contenu illicite, malveillant ou sans autorisation", "contourner les limites, droits d’accès ou mesures de sécurité", "perturber le Service, automatiser abusivement les accès ou tenter d’extraire des données non autorisées"]} />],
  ["Article 15 — Propriété intellectuelle", <p>Les éléments originaux Aétheria VTT restent la propriété de leurs titulaires. Aucune licence autre que le droit personnel d’utiliser le Service selon les présentes n’est accordée.</p>],
  ["Article 16 — Systèmes et contenus tiers", <p>Worlds Awakening, Glyphes et D&D/SRD restent soumis aux droits, autorisations et licences détaillés sur la page Crédits & licences. Aétheria VTT n’est pas un produit officiel Wizards of the Coast.</p>],
  ["Article 17 — Disponibilité du service", <p>Le Service est fourni selon les capacités techniques disponibles. Des interruptions, pertes de connexion ou limitations peuvent survenir, notamment sur les fonctions temps réel ou les services externes.</p>],
  ["Article 18 — Maintenance", <p>Des maintenances correctives, de sécurité ou d’évolution peuvent limiter temporairement l’accès. Un préavis sera donné lorsque cela est raisonnablement possible.</p>],
  ["Article 19 — Suspension d’un compte", <p>Un compte peut être limité ou suspendu en cas de risque de sécurité, fraude, violation grave ou répétée des présentes, ou obligation légale. L’utilisateur est informé lorsque la loi et la sécurité le permettent.</p>],
  ["Article 20 — Suppression d’un compte", <p>L’utilisateur peut demander la suppression depuis son profil ou par e-mail. La suppression affecte le profil, les personnages, campagnes et fichiers dont il est responsable ; les données devant être conservées légalement peuvent être archivées pendant la durée requise.</p>],
  ["Article 21 — Signalement de contenu", <><p>Une violation de droits d’auteur, un contenu illicite, une usurpation ou une violation des CGU peut être signalé ci-dessous. Ce parcours est distinct du bouton de signalement de bug.</p><LegalRequestForm type="content-report" /></>],
  ["Article 22 — Responsabilité", <p>Dans les limites permises par la loi, Aétheria VTT ne répond pas des dommages provenant d’un contenu utilisateur, d’un service tiers, d’un usage contraire aux CGU ou d’un événement hors de son contrôle.</p>],
  ["Article 23 — Données personnelles", <p>Les traitements sont détaillés dans la Politique de confidentialité. Ils sont limités aux fonctions effectivement utilisées.</p>],
  ["Article 24 — Cookies", <p>Le Service utilise des stockages nécessaires et, avec le choix de l’utilisateur, des préférences. Aucun outil statistique ou marketing n’est actuellement déclaré.</p>],
  ["Article 25 — Modification des CGU", <p>Les CGU peuvent évoluer pour refléter le Service, la loi ou la sécurité. La nouvelle version indique sa date et s’applique à compter de son entrée en vigueur.</p>],
  ["Article 26 — Droit applicable", <p>Les CGU sont soumises au droit français, sous réserve des protections impératives dont bénéficie le consommateur. Les parties chercheront d’abord une solution amiable.</p>],
  ["Article 27 — Contact", <p>Toute question peut être adressée à {contact}.</p>],
];

export function TermsOfUse() { return <LegalLayout title="Conditions Générales d’Utilisation" description="Règles applicables à l’accès et à l’utilisation d’Aétheria VTT." path="/cgu">{cguArticles.map(([title, body]) => <LegalSection key={title} title={title}>{body}</LegalSection>)}</LegalLayout>; }

export function TermsOfSale() {
  return <LegalLayout title="Conditions Générales de Vente" description="Conditions prévues pour les offres d’abonnement affichées par Aétheria VTT." path="/cgv">
    <div className="border border-primary/30 bg-primary/5 p-5"><strong className="text-primary">Information importante :</strong> Paddle est intégré en environnement de test uniquement. La commercialisation réelle reste inactive jusqu’à la vérification d’identité et la validation du site par Paddle.</div>
    <LegalSection title="1. Champ d’application"><p>Les présentes CGV encadreront la souscription en ligne aux services numériques Aétheria VTT par des consommateurs ou professionnels, lorsque le paiement sera activé.</p></LegalSection>
    <LegalSection title="2. Offres actuellement affichées"><LegalList items={["AÉTHERIA — 0 € à vie : 3 campagnes, 3 personnages, 5 joueurs par campagne et 5 Go.", "PREMIUM PJ — 2,99 €/mois, 8,49 €/3 mois ou 29,90 €/an : 20 personnages et 10 Go.", "PREMIUM MJ — 4,99 €/mois, 14,19 €/3 mois ou 49,90 €/an : 20 campagnes, 10 joueurs par campagne et 15 Go.", "PREMIUM MIXTE — 7,99 €/mois, 22,79 €/3 mois ou 79,90 €/an : 50 campagnes, 50 personnages, 10 joueurs par campagne et 30 Go."]} /><p>Le détail présenté avant validation, dont la périodicité et le total facturé, prévaut.</p></LegalSection>
    <LegalSection title="3. Prix et TVA"><p>Les prix sont affichés en euros. Régime de TVA applicable : <strong>[À COMPLÉTER avant activation des paiements]</strong>. Toute taxe applicable et le montant total devront être indiqués avant la commande.</p></LegalSection>
    <LegalSection title="4. Commande et acceptation"><p>Avant paiement, l’utilisateur devra voir l’offre, le prix, la périodicité, les fonctionnalités, limites, renouvellement et résiliation, puis accepter les CGV et CGU par une case non précochée. Le consentement cookies ou marketing ne sera pas associé à cette acceptation.</p></LegalSection>
    <LegalSection title="5. Paiement et facturation"><p>Paddle est le prestataire de paiement et agit comme marchand officiel. Il traite les moyens de paiement, taxes, factures et reçus selon ses propres conditions. Aétheria VTT ne collecte pas les données complètes de carte. L’intégration est actuellement limitée au test.</p></LegalSection>
    <LegalSection title="6. Durée, renouvellement et résiliation"><p>Les offres payantes se renouvellent mensuellement, tous les trois mois ou annuellement selon le choix affiché avant commande. La résiliation est disponible depuis le portail Paddle ouvert par « Gérer mon abonnement ». L’accès Premium reste acquis jusqu’à la fin de la période payée.</p></LegalSection>
    <LegalSection title="7. Changement d’offre, suspension et fin"><p>Les règles de proratisation, changement, impayé, suspension et fin d’abonnement sont <strong>[À COMPLÉTER avant activation]</strong>. Aucune suppression automatique des contenus excédant les quotas ne doit intervenir sans information préalable et délai raisonnable.</p></LegalSection>
    <LegalSection title="8. Remboursement"><p>Hors exercice valable du droit de rétractation ou garantie légale, les modalités de remboursement sont <strong>[À COMPLÉTER avant activation]</strong>. Les droits légaux du consommateur ne peuvent être exclus.</p></LegalSection>
    <LegalSection title="9. Droit de rétractation"><p>Le consommateur dispose en principe de quatorze jours à compter de la conclusion du contrat à distance. Les conditions liées au commencement anticipé sont détaillées sur la page <Link className="text-primary underline" to="/retractation">Rétractation</Link>. Aucune renonciation automatique n’est appliquée.</p></LegalSection>
    <LegalSection title="10. Contact et litiges"><p>Réclamations : {contact}. Médiateur de la consommation : <strong>[À COMPLÉTER avant commercialisation]</strong>. Le droit français s’applique sous réserve des règles impératives protégeant le consommateur.</p></LegalSection>
  </LegalLayout>;
}

export function PrivacyPolicy() {
  return <LegalLayout title="Politique de confidentialité" description="Traitements de données réellement identifiés dans Aétheria VTT et droits des utilisateurs." path="/confidentialite">
    <LegalSection title="1. Responsable du traitement">{identity}</LegalSection>
    <LegalSection title="2 à 10. Données collectées"><LegalList items={["Compte et connexion : adresse e-mail, identifiant technique, mot de passe traité par le service d’authentification, informations Google si cette connexion est choisie, dates et journaux de sécurité.", "Profil : nom d’aventurier facultatif, avatar et date de création.", "Campagnes : titre, description, système, membres, invitations, paramètres, messages, notes partagées, scènes, sessions et états de jeu.", "Personnages : identité de jeu, système, caractéristiques, équipement, ressources et fiche associée.", "Fichiers importés : avatars, images, cartes, tokens, PDF, documents, audio et métadonnées techniques.", "Données techniques : adresse IP et agent utilisateur dans les journaux techniques et signalements, URL, langue, plateforme et taille d’écran lors d’un rapport de bug.", "Données de paiement : aucune donnée de paiement collectée actuellement ; aucun prestataire de paiement intégré.", "IA : instructions et contexte expressément envoyés aux assistants MJ, générateurs d’entités, journaux de session ou traduction du Codex."]} /></LegalSection>
    <LegalSection title="11. Finalités"><LegalList items={["créer, sécuriser et administrer le compte", "fournir les campagnes, personnages, VTT, Codex et stockage", "synchroniser les parties et gérer les invitations et notifications", "répondre aux signalements, demandes juridiques et incidents", "générer les contenus demandés via les fonctions d’intelligence artificielle", "prévenir les abus et maintenir la sécurité"]} /></LegalSection>
    <LegalSection title="12. Bases légales"><p>Exécution du contrat ou mesures précontractuelles pour fournir le Service ; intérêt légitime pour la sécurité, la prévention des abus et l’amélioration technique ; obligation légale pour les demandes et archives imposées ; consentement pour les préférences facultatives et, lorsqu’il est requis, certains traitements optionnels.</p></LegalSection>
    <LegalSection title="13. Durées de conservation"><p>Les données de compte et de jeu sont conservées pendant l’utilisation du compte, puis supprimées ou anonymisées après la demande et les délais techniques nécessaires. Les journaux de sécurité, preuves de demande, éventuelles données de facturation et données exigées par la loi sont conservés pendant leurs durées utiles ou légales. Les durées chiffrées finales sont <strong>[À COMPLÉTER après validation juridique]</strong>.</p></LegalSection>
    <LegalSection title="14. Destinataires"><p>Les données sont accessibles à l’utilisateur, aux participants autorisés d’une campagne, à l’éditeur lorsque nécessaire pour l’assistance et la sécurité, et aux prestataires ci-dessous dans la limite de leur mission.</p></LegalSection>
    <LegalSection title="15 à 17. Sous-traitants, hébergement et transferts"><div className="overflow-x-auto"><table className="w-full min-w-[640px] border-collapse text-left text-xs"><thead><tr className="border-b border-primary/30"><th className="p-3">Service vérifié</th><th className="p-3">Fonction et données</th><th className="p-3">Transferts</th></tr></thead><tbody>{[
      ["Lovable Labs AB / Lovable Cloud", "Hébergement du site et infrastructure gérée : authentification, base, stockage, fonctions, temps réel et envoi d’e-mails géré.", "Société établie en Suède. Localisation complète des traitements et sous-traitants ultérieurs : [À COMPLÉTER]."],
      ["Google", "Connexion OAuth choisie par l’utilisateur : identité Google, nom et adresse e-mail.", "Des traitements hors UE peuvent intervenir selon les conditions de Google."],
      ["Lovable AI Gateway et Google Gemini", "Fonctions IA demandées par l’utilisateur : prompts et contexte utile de campagne ou de contenu.", "Localisation et garanties contractuelles détaillées : [À COMPLÉTER]."],
      ["Open5e", "Consultation de données publiques D&D 5e/SRD ; aucune donnée personnelle n’est volontairement transmise dans les requêtes prévues.", "Service tiers ; hébergement exact : NON VÉRIFIÉ."],
      ["Paddle", "Paiement, abonnements, facturation, taxes et portail client lors d’une souscription payante.", "Traitements et transferts régis par la politique de confidentialité de Paddle."],
    ].map((row) => <tr key={row[0]} className="border-b border-border/50 align-top">{row.map((cell) => <td key={cell} className="p-3">{cell}</td>)}</tr>)}</tbody></table></div><p>Le prestataire technique final derrière l’envoi d’e-mails géré n’est pas identifiable dans le code : <strong>NON VÉRIFIÉ</strong>. Aucun outil d’analytics ou traceur publicitaire n’a été identifié.</p></LegalSection>
    <LegalSection title="18. Sécurité"><p>Des contrôles d’accès, règles de permission, liens temporaires pour les fichiers privés, validation des entrées et journalisation sont utilisés. Aucun système ne garantit un risque nul ; tout incident suspect peut être signalé.</p></LegalSection>
    <LegalSection title="19. Vos droits"><p>Selon votre situation : accès, rectification, effacement, limitation, opposition, portabilité lorsqu’elle s’applique, retrait du consentement et définition de directives relatives au sort de vos données. Le retrait n’affecte pas la licéité des traitements antérieurs.</p><LegalRequestForm type="data-rights" /></LegalSection>
    <LegalSection title="20. Suppression du compte"><p>La demande entraîne l’examen de la suppression du profil, des personnages, campagnes, fichiers et appartenances. Les effets sur les campagnes partagées sont vérifiés avant exécution. Les éléments imposés par une obligation légale ou nécessaires à la défense de droits peuvent être isolés et conservés temporairement.</p></LegalSection>
    <LegalSection title="21. Réclamation auprès de la CNIL"><p>Vous pouvez saisir la Commission nationale de l’informatique et des libertés : <a className="text-primary underline" href="https://www.cnil.fr" target="_blank" rel="noreferrer">www.cnil.fr</a>.</p></LegalSection>
    <LegalSection title="22. Contact"><p>{contact}</p></LegalSection><LegalSection title="23. Mise à jour"><p>Cette politique sera mise à jour lors de l’activation d’un paiement, d’un nouvel outil de mesure, d’un nouveau prestataire ou d’un changement substantiel des traitements.</p></LegalSection>
  </LegalLayout>;
}

export function CookiesPolicy() {
  return <LegalLayout title="Politique cookies" description="Cookies et stockages locaux réellement identifiés dans la version actuelle d’Aétheria VTT." path="/cookies">
    <LegalSection title="1. Portée"><p>Le terme « cookies » couvre ici les cookies techniques et les technologies de stockage local du navigateur. L’audit du code n’a identifié aucun outil de mesure d’audience, aucune publicité et aucun pixel marketing.</p></LegalSection>
    <LegalSection title="2. Nécessaires"><LegalList items={["session d’authentification et protection de l’accès, gérées par l’infrastructure d’authentification", "aetheria.cookie-consent.v1 : mémorise le choix de cookies", "stockages temporaires indispensables à certains états de jeu et à la stabilité de l’interface"]} /><p>Ils ne peuvent pas être désactivés depuis le bandeau lorsqu’ils sont strictement nécessaires au service demandé.</p></LegalSection>
    <LegalSection title="3. Préférences facultatives"><LegalList items={["aetheria.remember.credentials : mémorisation de l’adresse e-mail", "aetheria.ambient.muted et préférences audio", "grille, unité de mesure et affichage du VTT par campagne", "état du tutoriel, cosmétiques et préférences d’interface", "notes locales du MJ et certains états locaux de jeu sur l’appareil"]} /><p>Le refus supprime les principales préférences globales et empêche leur activation volontaire via le bandeau. Certaines préférences créées directement par une action demandée dans le VTT restent nécessaires à cette action.</p></LegalSection>
    <LegalSection title="4. Statistiques et marketing"><p>Aucun cookie ou traceur statistique, marketing ou publicitaire n’a été identifié ou activé.</p></LegalSection>
    <LegalSection title="5. Modifier ou retirer votre choix"><p>Utilisez « Paramètres des cookies » dans le pied de page à tout moment. Refuser les préférences n’empêche pas l’accès aux fonctions essentielles, mais réinitialise certains réglages locaux.</p></LegalSection>
    <LegalSection title="6. Durée"><p>Les préférences restent sur l’appareil jusqu’à leur suppression par l’utilisateur, le navigateur ou une nouvelle sélection. La durée des éventuels éléments de session est limitée par le mécanisme d’authentification.</p></LegalSection>
  </LegalLayout>;
}

export function CreditsLicenses() {
  return <LegalLayout title="Crédits & licences" description="Origine, propriété et licences des systèmes et ressources actuellement présentés par Aétheria VTT." path="/credits-licences">
    <LegalSection title="Aétheria"><p>Aétheria est le système et l’univers développés par Aétheria VTT / Erwan Didier Valery Lesage. Les règles, l’univers, le bestiaire, les classes, les races, les logos, les illustrations originales et les contenus numériques originaux Aétheria appartiennent à leurs titulaires et ne sont pas attribués à un tiers.</p></LegalSection>
    <LegalSection title="Worlds Awakening"><p>Worlds Awakening est une création de Nicolas BÉDÉ, concepteur du jeu, avec la collaboration de Christian BERNARD pour l’élaboration du lore.</p><p>Les éléments appartenant à Worlds Awakening restent la propriété de leurs ayants droit.</p><p>Aétheria VTT dispose d’une autorisation accordée directement par les créateurs de Worlds Awakening pour l’utilisation des éléments concernés sur la plateforme. Cette mention ne doit pas être comprise comme étendant l’autorisation au-delà des éléments effectivement autorisés.</p></LegalSection>
    <LegalSection title="Glyphes"><p>Glyphes est un jeu de rôle francophone créé par Aiodos Studio 1D / Aiodos.</p><p>Aétheria VTT utilise le système Glyphes avec l’autorisation de son créateur.</p><p>Les règles, l’univers, les textes, illustrations, marques, logos et autres éléments propres à Glyphes restent la propriété de leurs ayants droit. Aétheria VTT n’est pas propriétaire de Glyphes et ne revendique aucun droit de propriété sur le jeu ou ses éléments.</p></LegalSection>
    <LegalSection title="D&D 5e — SRD 5.1"><p>Le contenu SRD 5.1 utilisé est mis à disposition sous licence Creative Commons Attribution 4.0 International (CC BY 4.0).</p><blockquote className="border-l-2 border-primary/50 pl-4 italic">This work includes material taken from the System Reference Document 5.1 (“SRD 5.1”) by Wizards of the Coast LLC and available at https://dnd.wizards.com/resources/systems-reference-document. The SRD 5.1 is licensed under the Creative Commons Attribution 4.0 International License available at https://creativecommons.org/licenses/by/4.0/legalcode.</blockquote><p>Wizards of the Coast LLC est le détenteur des droits concernés. D&D, Donjons & Dragons et les marques associées appartiennent à leurs détenteurs respectifs. Aétheria VTT n’est pas affilié à, sponsorisé ou approuvé par Wizards of the Coast.</p></LegalSection>
    <LegalSection title="Ressources logicielles et externes"><LegalList items={["Open5e : interface de consultation de données SRD ; les licences restent celles indiquées par leurs sources.", "Lucide : bibliothèque d’icônes utilisée dans l’interface, sous licence ISC.", "React, Vite, Tailwind CSS et composants open source : utilisés selon leurs licences respectives.", "Google Fonts : Cinzel et Lora sont chargées pour la typographie ; leurs licences restent celles publiées par leurs auteurs."]} /><p>L’origine et les droits de chaque image ou piste audio non accompagnée d’une preuve dans le projet restent <strong>NON VÉRIFIÉS</strong> et doivent être documentés avant commercialisation.</p></LegalSection>
    <LegalSection title="Marques et systèmes tiers"><p>Les noms, marques, logos, univers et contenus tiers restent la propriété de leurs détenteurs respectifs. Aétheria VTT ne revendique pas leur propriété. Une autorisation spécifique n’est présentée que lorsqu’elle a été déclarée par le titulaire du projet.</p></LegalSection>
  </LegalLayout>;
}

export function Withdrawal() {
  return <LegalLayout title="Droit de rétractation" description="Informations et formulaire permettant au consommateur d’exercer son droit de rétractation." path="/retractation">
    <LegalSection title="Principe"><p>Lorsqu’il est applicable, le consommateur dispose d’un délai de quatorze jours à compter de la conclusion du contrat à distance pour notifier sa rétractation, sans avoir à motiver sa décision.</p></LegalSection>
    <LegalSection title="Commencement anticipé"><p>Si le consommateur demande expressément que le service commence avant la fin du délai, cette demande ne supprime pas automatiquement son droit. En cas de rétractation après le début demandé, un montant proportionnel au service effectivement fourni peut être dû lorsque la loi le permet et que l’information préalable a été donnée.</p><p>La perte du droit pour un contenu numérique sans support matériel suppose les conditions légales applicables, notamment un accord préalable exprès et une reconnaissance expresse lorsque la loi l’exige. Aucune renonciation n’est présumée.</p></LegalSection>
    <LegalSection title="Effets"><p>Après une demande valable, les sommes concernées sont remboursées selon le moyen et le délai légaux, sous réserve des exceptions et montants proportionnels applicables. Les modalités finales devront être synchronisées avec le futur moyen de paiement.</p></LegalSection>
    <LegalRequestForm type="withdrawal" />
  </LegalLayout>;
}