// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-campaigns.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-campaigns.ts
var list_campaigns_default = defineTool({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List the Aetheria VTT campaigns the signed-in user can access (owned as GM or joined as player).",
  inputSchema: {
    limit: z.number().int().optional().describe("Maximum number of campaigns to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    const { data, error } = await supabase.from("campaigns").select("id, title, system, description, summary, is_active, level_min, level_max, max_players, schedule, created_at, user_id").order("updated_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const userId = ctx.getUserId();
    const rows = (data ?? []).map((c) => ({ ...c, is_gm: c.user_id === userId }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { campaigns: rows }
    };
  }
});

// src/lib/mcp/tools/get-campaign.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_campaign_default = defineTool2({
  name: "get_campaign",
  title: "Get campaign details",
  description: "Get one Aetheria VTT campaign with its members (display name, role and linked character), if the signed-in user has access to it.",
  inputSchema: { campaign_id: z2.string().describe("UUID of the campaign.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ campaign_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: campaign, error } = await supabase.from("campaigns").select("*").eq("id", campaign_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!campaign) {
      return { content: [{ type: "text", text: "Campaign not found or not accessible" }], isError: true };
    }
    const { data: members } = await supabase.from("campaign_members").select("user_id, role, character_id, joined_at").eq("campaign_id", campaign_id);
    const userIds = Array.from(new Set((members ?? []).map((m) => m.user_id).filter(Boolean)));
    const charIds = Array.from(
      new Set((members ?? []).map((m) => m.character_id).filter(Boolean))
    );
    const [profilesRes, charsRes] = await Promise.all([
      userIds.length ? supabase.from("profiles").select("user_id, display_name").in("user_id", userIds) : Promise.resolve({ data: [] }),
      charIds.length ? supabase.from("characters").select("id, name, class, level").in("id", charIds) : Promise.resolve({ data: [] })
    ]);
    const profileMap = new Map((profilesRes.data ?? []).map((p) => [p.user_id, p]));
    const charMap = new Map((charsRes.data ?? []).map((c) => [c.id, c]));
    const enriched = (members ?? []).map((m) => ({
      user_id: m.user_id,
      role: m.role,
      display_name: profileMap.get(m.user_id)?.display_name ?? null,
      character: m.character_id ? charMap.get(m.character_id) ?? null : null,
      joined_at: m.joined_at
    }));
    const payload = { campaign, members: enriched };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-characters.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_characters_default = defineTool3({
  name: "list_characters",
  title: "List characters",
  description: "List the characters owned by the signed-in user, across all game systems.",
  inputSchema: {
    limit: z3.number().int().optional().describe("Maximum number of characters to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    const { data, error } = await supabase.from("characters").select("id, name, race, class, subclass, level, hp, max_hp, armor_class, system").eq("user_id", ctx.getUserId() ?? "").order("updated_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { characters: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-character.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_character_default = defineTool4({
  name: "get_character",
  title: "Get character sheet",
  description: "Get the full character sheet (stats, system data, background) of a character the signed-in user can access.",
  inputSchema: { character_id: z4.string().describe("UUID of the character.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ character_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("characters").select("*").eq("id", character_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Character not found or not accessible" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { character: data }
    };
  }
});

// src/lib/mcp/tools/list-campaign-notes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_campaign_notes_default = defineTool5({
  name: "list_campaign_notes",
  title: "List campaign notes",
  description: "List the notes of a campaign that the signed-in user is allowed to read (GM-only notes require the GM role).",
  inputSchema: {
    campaign_id: z5.string().describe("UUID of the campaign."),
    limit: z5.number().int().optional().describe("Maximum number of notes to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ campaign_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    const { data, error } = await supabase.from("campaign_notes").select("id, title, content, is_gm_only, created_at, updated_at").eq("campaign_id", campaign_id).order("updated_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-campaign-note.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var create_campaign_note_default = defineTool6({
  name: "create_campaign_note",
  title: "Create campaign note",
  description: "Create a note in a campaign on behalf of the signed-in user (session prep, lore, recap). Can be marked GM-only.",
  inputSchema: {
    campaign_id: z6.string().describe("UUID of the campaign."),
    title: z6.string().describe("Title of the note."),
    content: z6.string().describe("Body of the note (plain text or markdown)."),
    is_gm_only: z6.boolean().optional().describe("Restrict the note to the GM (default false).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ campaign_id, title, content, is_gm_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("campaign_notes").insert({
      campaign_id,
      user_id: ctx.getUserId(),
      title: title.trim(),
      content,
      is_gm_only: is_gm_only ?? false
    }).select("id, title, is_gm_only, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "snawpxrejmcxfbiiowxr";
var mcp_default = defineMcp({
  name: "vtt-jdr",
  title: "VTT JDR",
  version: "0.1.0",
  instructions: "Outils pour Aetheria VTT (table de jeu de r\xF4le virtuelle). Permet de lister et consulter les campagnes, leurs membres, les fiches de personnage de l'utilisateur connect\xE9, ainsi que de lire et cr\xE9er des notes de campagne. Chaque appel agit au nom de l'utilisateur connect\xE9 et respecte ses permissions (MJ / joueur).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_campaigns_default,
    get_campaign_default,
    list_characters_default,
    get_character_default,
    list_campaign_notes_default,
    create_campaign_note_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
